cabal-version:      3.0
name:               lambdaSearch
version:            0.1.0.0
license:            AGPL-3.0-or-later
license-file:       LICENSE
author:             Martin Elde Knutsen
maintainer:         maknu0536@uib.no
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall -threaded -XViewPatterns -XOverloadedStrings  -XLambdaCase
library
    -- Import common warning flags.
    import:           warnings
    exposed-modules: 
                      TraversalSettings
                    , TraversalFunctions
                    , PrintFunctions
                    , ParseInput

    build-depends:    text ^>=2.0.2
                    , base ^>=4.18.3.0
                    , mtl
                    , ansi-terminal
                    , unix
                    , bytestring
                    , filepath
                    , posix-paths
                    , unliftio
                    , async
                    , regex-tdfa ^>= 1.3.2
                    , filepath-bytestring
                    , process
                    , megaparsec


    hs-source-dirs:   src

    default-language: GHC2021


executable lambdaSearch
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.18.3.0,
        lambdaSearch,
    hs-source-dirs:   app
    default-language: GHC2021

test-suite lambdaSearch-test

    import:           warnings

    default-language: GHC2021

    type:             exitcode-stdio-1.0

    hs-source-dirs:   test

    main-is:          Main.hs
    other-modules:
          TreverselSettingsTest
        , TraverselFunctionsTest
        , ParserTest
        , Utils


    build-depends:
          directory 
        , unix
        , posix-paths
        , base 
        , lambdaSearch
        , tasty
        , tasty-hunit
        , tasty-quickcheck
        , bytestring
        , temporary     

        
