cabal-version:      3.0
name:               lambdaSearch
version:            0.1.0.0
license:            AGPL-3.0-or-later
license-file:       LICENSE
author:             Martin Elde Knutsen
maintainer:         maknu0536@uib.no
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall -threaded -XViewPatterns -XOverloadedStrings  -XLambdaCase
library
    -- Import common warning flags.
    import:           warnings
    exposed-modules: 
                      TraversalSettings
                    , TraverselsFunctions
                    , PrintFunctions
                    , ParseInput
                    , SearchTUI

    build-depends:    text ^>=2.0.2
                    , base ^>=4.18.3.0
                    , mtl
                    , ansi-terminal
                    , unix
                    , bytestring
                    , filepath
                    , posix-paths
                    , unliftio
                    , stm
                    , async
                    , regex-tdfa ^>= 1.3.2
                    , filepath-bytestring
                    , process
                    , megaparsec
                    , brick
                    , microlens
                    , vty


    hs-source-dirs:   src

    default-language: GHC2021


executable lambdaSearch
    -- Import common warning flags.
    import:           warnings

    -- .hs or .lhs file containing the Main module.
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    -- Other library packages from which modules are imported.
    build-depends:
        base ^>=4.18.3.0,
        lambdaSearch,

    -- Directories containing source files.
    hs-source-dirs:   app

    -- Base language which the package is written in.
    default-language: GHC2021

test-suite lambdaSearch-test

    import:           warnings

    default-language: GHC2021

    type:             exitcode-stdio-1.0

    hs-source-dirs:   test

    main-is:          Main.hs
    other-modules:
          TreverselSettingsTest
        , TraverselFunctionsTest
        , ParserTest


    build-depends:
          directory 
        , unix
        , posix-paths
        , base 
        , lambdaSearch
        , tasty
        , tasty-hunit
        , tasty-quickcheck
        , bytestring
        , temporary     

        
