name:                 lambdaSearch
version:              0.1.0.0
visibility:           public
id:                   lambdaSearch-0.1.0.0-inplace
key:                  lambdaSearch-0.1.0.0-inplace
license:              AGPL-3.0-or-later
maintainer:           maknu0536@uib.no
author:               Martin Elde Knutsen
abi:                  inplace
exposed:              True
exposed-modules:      FileTreversal SearchFiles TreveseFunctions
import-dirs:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/build

library-dirs:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/build

library-dirs-static:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/build

dynamic-library-dirs:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/build

data-dir:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/.

hs-libraries:         HSlambdaSearch-0.1.0.0-inplace
depends:
    sync-2.2.6-e91dcb57 base-4.18.3.0 bytestring-0.11.5.4
    filepath-1.4.301.0 mtl-2.3.1 psx-pths-0.3.0.0-4d08f264 stm-2.5.1.0
    unix-2.8.6.0 nlft-0.2.25.1-3d3242d7

haddock-interfaces:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/doc/html/lambdaSearch/lambdaSearch.haddock

haddock-html:
    /Users/martineldeknutsen/Dev/UiB/inf221/semesterProjekt/lambdaSearch/dist-newstyle/build/aarch64-osx/ghc-9.6.7/lambdaSearch-0.1.0.0/doc/html/lambdaSearch
